### ISSUE TITLE
New file types to add

### ISSUE THREAD

**Issue by BrennanHCSC** [hc-sc-ocdo-bdpd/file-processing-tools#113]
Add functionality for:
- gif
- tif
- python
- pst,
- heic
- audio/video file types

**Comment by benjaminLuoHC** [comment]
Support for `.pst` files is tricky. It must be done through a Python library (`libratom`, `libpff-python`, `Aspose.Email-for-Python-via-NET`, or `pywin32`). I could only get `pywin32` to work, but this one forces Outlook to run in the background. Further, since the `File` instance is open in the background, `File.processor.save()` will be unable to copy the file (as it would be currently in-use)

**Comment by benjaminLuoHC** [comment]
Addressed in PR #126 

PST file support is excluded from this PR, but the code is functional and in the `enhancement/pst-file-type` branch
