### ISSUE TITLE
GUI executable

### ISSUE THREAD

**Issue by pgaviganHC** [hc-sc-ocdo-bdpd/file-processing-tools#71]
A build process has been setup for a standalone exe of a console app for clients to use the table processing tool. This needs to be expanded to also generate an exe of the GUI.

**Comment by erikafung20** [comment]
I think the problem is due to dash callback: https://github.com/plotly/dash/issues/1885
Tried this tutorial (https://github.com/JonThom/dash-background-callbacks-pyinstaller) but got the same error when I open the exe

  File "dash\_callback.py", line 318, in wrap_func
  File "dash\long_callback\managers\__init__.py", line 83, in register_func
  File "dash\long_callback\managers\__init__.py", line 103, in hash_function
  File "inspect.py", line 1147, in getsource
  File "inspect.py", line 1129, in getsourcelines
  File "inspect.py", line 958, in findsource
OSError: could not get source code

**Comment by fnwaohaHC** [comment]
So far exe is made and GUI opens but there is an issue with the call backs. Nothing happens once you submit a file.

Steps taken so far:
  - Recreate the venv before running the build
  - Run build.py
  
  Add these lines to the GUI.spec file:
  - datas += [('table_processing\long_callbacks.py', '.'), ('cache', 'cache')] (line 25)
  - datas += [('.venv\\Lib\\site-packages\\torchvision', 'torchvision')] (line 26)
  
  Then type in terminal:
  - pyinstaller --noconfirm GUI.spec

**Comment by erikafung20** [comment]
Solved with #78
