### ISSUE TITLE
Temporary files

### ISSUE THREAD

**Issue by BrennanHCSC** [hc-sc-ocdo-bdpd/file-processing-tools#86]
- Add method to handle temporary files
- This will likely entail modifying _get_processor in file.py to handle if a ~ is at the end of the extension

**Comment by pgaviganHC** [comment]
@BrennanHCSC Has this issue been resolved?

**Comment by benjaminLuoHC** [comment]
Temporary files (at least `.tmp`, `.dat` and other system-generated file types) are handled by the generic processor. However, temporary files that are currently open will crash the program due to permission errors

For example, having an `.xlsx` file open will generate a `~[file_name].xlsx` file and trying to open this with `File([file_name])` will error

**Comment by pgaviganHC** [comment]
> Temporary files (at least `.tmp`, `.dat` and other system-generated file types) are handled by the generic processor. However, temporary files that are currently open will crash the program due to permission errors
> 
> For example, having an `.xlsx` file open will generate a `~[file_name].xlsx` file and trying to open this with `File([file_name])` will error

Can we add relevant try/catch blocks to protect from this?

**Comment by benjaminLuoHC** [comment]
The `Directory` processor will catch it like it does with corrupted files and indicate `error: PermissionError` in the report
